# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from pyst_client.models.node import Node
from typing import Optional, Set
from typing_extensions import Self

class AssociationInput(BaseModel):
    """
    AssociationInput
    """ # noqa: E501
    id: StrictStr = Field(description="https://www.w3.org/TR/json-ld/#node-identifiers", alias="@id")
    type: List[StrictStr] = Field(description="https://www.w3.org/TR/json-ld/#specifying-the-type", alias="@type")
    http___rdf_vocabulary_ddialliance_org_xkossource_concept: Annotated[List[Node], Field(min_length=1)] = Field(description="https://rdf-vocabulary.ddialliance.org/xkos.html#correspondences", alias="http://rdf-vocabulary.ddialliance.org/xkos#sourceConcept")
    http___rdf_vocabulary_ddialliance_org_xkostarget_concept: Annotated[List[Node], Field(min_length=1)] = Field(description="https://rdf-vocabulary.ddialliance.org/xkos.html#correspondences", alias="http://rdf-vocabulary.ddialliance.org/xkos#targetConcept")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["@id", "@type", "http://rdf-vocabulary.ddialliance.org/xkos#sourceConcept", "http://rdf-vocabulary.ddialliance.org/xkos#targetConcept"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssociationInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in http___rdf_vocabulary_ddialliance_org_xkossource_concept (list)
        _items = []
        if self.http___rdf_vocabulary_ddialliance_org_xkossource_concept:
            for _item_http___rdf_vocabulary_ddialliance_org_xkossource_concept in self.http___rdf_vocabulary_ddialliance_org_xkossource_concept:
                if _item_http___rdf_vocabulary_ddialliance_org_xkossource_concept:
                    _items.append(_item_http___rdf_vocabulary_ddialliance_org_xkossource_concept.to_dict())
            _dict['http://rdf-vocabulary.ddialliance.org/xkos#sourceConcept'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in http___rdf_vocabulary_ddialliance_org_xkostarget_concept (list)
        _items = []
        if self.http___rdf_vocabulary_ddialliance_org_xkostarget_concept:
            for _item_http___rdf_vocabulary_ddialliance_org_xkostarget_concept in self.http___rdf_vocabulary_ddialliance_org_xkostarget_concept:
                if _item_http___rdf_vocabulary_ddialliance_org_xkostarget_concept:
                    _items.append(_item_http___rdf_vocabulary_ddialliance_org_xkostarget_concept.to_dict())
            _dict['http://rdf-vocabulary.ddialliance.org/xkos#targetConcept'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssociationInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "http://rdf-vocabulary.ddialliance.org/xkos#sourceConcept": [Node.from_dict(_item) for _item in obj["http://rdf-vocabulary.ddialliance.org/xkos#sourceConcept"]] if obj.get("http://rdf-vocabulary.ddialliance.org/xkos#sourceConcept") is not None else None,
            "http://rdf-vocabulary.ddialliance.org/xkos#targetConcept": [Node.from_dict(_item) for _item in obj["http://rdf-vocabulary.ddialliance.org/xkos#targetConcept"]] if obj.get("http://rdf-vocabulary.ddialliance.org/xkos#targetConcept") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


