# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CorrespondenceOutput(BaseModel):
    """
    CorrespondenceOutput
    """ # noqa: E501
    id: StrictStr = Field(description="https://www.w3.org/TR/json-ld/#node-identifiers", alias="@id")
    type: List[StrictStr] = Field(description="https://www.w3.org/TR/json-ld/#specifying-the-type", alias="@type")
    http___www_w3_org_2004_02_skos_corepref_label: List[Dict[str, StrictStr]] = Field(description="https://www.w3.org/TR/skos-primer/#secpref", alias="http://www.w3.org/2004/02/skos/core#prefLabel")
    http___purl_org_ontology_bibo_status: List[Dict[str, StrictStr]] = Field(description="https://github.com/dcmi/bibo/blob/main/rdf/bibo.ttl#L391", alias="http://purl.org/ontology/bibo/status")
    http___www_w3_org_2004_02_skos_coredefinition: Optional[List[Dict[str, StrictStr]]] = Field(default=None, description="https://www.w3.org/TR/skos-primer/#secdocumentation", alias="http://www.w3.org/2004/02/skos/core#definition")
    http___www_w3_org_2004_02_skos_corenotation: Optional[List[Dict[str, StrictStr]]] = Field(default=None, description="https://www.w3.org/TR/skos-primer/#secnotations", alias="http://www.w3.org/2004/02/skos/core#notation")
    http___www_w3_org_2004_02_skos_corechange_note: Optional[List[Dict[str, Any]]] = Field(default=None, alias="http://www.w3.org/2004/02/skos/core#changeNote")
    http___www_w3_org_2004_02_skos_corehistory_note: Optional[List[Dict[str, Any]]] = Field(default=None, alias="http://www.w3.org/2004/02/skos/core#historyNote")
    http___www_w3_org_2004_02_skos_coreeditorial_note: Optional[List[Dict[str, Any]]] = Field(default=None, alias="http://www.w3.org/2004/02/skos/core#editorialNote")
    http___purl_org_dc_terms_created: List[Dict[str, Any]] = Field(description="https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/created", alias="http://purl.org/dc/terms/created")
    http___purl_org_dc_terms_creator: List[Dict[str, Any]] = Field(description="https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/elements/1.1/creator", alias="http://purl.org/dc/terms/creator")
    http___www_w3_org_2002_07_owlversion_info: List[Dict[str, Any]] = Field(description="https://www.w3.org/TR/owl-ref/#versionInfo-def", alias="http://www.w3.org/2002/07/owl#versionInfo")
    http___rdf_vocabulary_ddialliance_org_xkoscompares: List[Dict[str, Any]] = Field(description="https://rdf-vocabulary.ddialliance.org/xkos.html#correspondences", alias="http://rdf-vocabulary.ddialliance.org/xkos#compares")
    http___rdf_vocabulary_ddialliance_org_xkosmade_of: Optional[List[Dict[str, Any]]] = Field(default=None, description="https://www.w3.org/TR/skos-primer/#secdocumentation", alias="http://rdf-vocabulary.ddialliance.org/xkos#madeOf")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["@id", "@type", "http://www.w3.org/2004/02/skos/core#prefLabel", "http://purl.org/ontology/bibo/status", "http://www.w3.org/2004/02/skos/core#definition", "http://www.w3.org/2004/02/skos/core#notation", "http://www.w3.org/2004/02/skos/core#changeNote", "http://www.w3.org/2004/02/skos/core#historyNote", "http://www.w3.org/2004/02/skos/core#editorialNote", "http://purl.org/dc/terms/created", "http://purl.org/dc/terms/creator", "http://www.w3.org/2002/07/owl#versionInfo", "http://rdf-vocabulary.ddialliance.org/xkos#compares", "http://rdf-vocabulary.ddialliance.org/xkos#madeOf"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CorrespondenceOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CorrespondenceOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "http://www.w3.org/2004/02/skos/core#prefLabel": obj.get("http://www.w3.org/2004/02/skos/core#prefLabel"),
            "http://purl.org/ontology/bibo/status": obj.get("http://purl.org/ontology/bibo/status"),
            "http://www.w3.org/2004/02/skos/core#definition": obj.get("http://www.w3.org/2004/02/skos/core#definition"),
            "http://www.w3.org/2004/02/skos/core#notation": obj.get("http://www.w3.org/2004/02/skos/core#notation"),
            "http://www.w3.org/2004/02/skos/core#changeNote": obj.get("http://www.w3.org/2004/02/skos/core#changeNote"),
            "http://www.w3.org/2004/02/skos/core#historyNote": obj.get("http://www.w3.org/2004/02/skos/core#historyNote"),
            "http://www.w3.org/2004/02/skos/core#editorialNote": obj.get("http://www.w3.org/2004/02/skos/core#editorialNote"),
            "http://purl.org/dc/terms/created": obj.get("http://purl.org/dc/terms/created"),
            "http://purl.org/dc/terms/creator": obj.get("http://purl.org/dc/terms/creator"),
            "http://www.w3.org/2002/07/owl#versionInfo": obj.get("http://www.w3.org/2002/07/owl#versionInfo"),
            "http://rdf-vocabulary.ddialliance.org/xkos#compares": obj.get("http://rdf-vocabulary.ddialliance.org/xkos#compares"),
            "http://rdf-vocabulary.ddialliance.org/xkos#madeOf": obj.get("http://rdf-vocabulary.ddialliance.org/xkos#madeOf")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


