# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DateTimeType(str, Enum):
    """
    DateTimeType
    """

    """
    allowed enum values
    """
    HTTP_COLON_SLASH_SLASH_WWW_DOT_W3_DOT_ORG_SLASH_2001_SLASH_XML_SCHEMA_HASH_DATE = 'http://www.w3.org/2001/XMLSchema#date'
    HTTP_COLON_SLASH_SLASH_WWW_DOT_W3_DOT_ORG_SLASH_2001_SLASH_XML_SCHEMA_HASH_DATE_TIME = 'http://www.w3.org/2001/XMLSchema#dateTime'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DateTimeType from a JSON string"""
        return cls(json.loads(json_str))


