# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RelationshipOutput(BaseModel):
    """
    RelationshipOutput
    """ # noqa: E501
    id: StrictStr = Field(description="https://www.w3.org/TR/json-ld/#node-identifiers", alias="@id")
    http___www_w3_org_2004_02_skos_corebroader: Optional[List[Dict[str, Any]]] = Field(default=None, description="https://www.w3.org/TR/skos-primer/#sechierarchy", alias="http://www.w3.org/2004/02/skos/core#broader")
    http___www_w3_org_2004_02_skos_corenarrower: Optional[List[Dict[str, Any]]] = Field(default=None, description="https://www.w3.org/TR/skos-primer/#sechierarchy", alias="http://www.w3.org/2004/02/skos/core#narrower")
    http___www_w3_org_2004_02_skos_coreexact_match: Optional[List[Dict[str, Any]]] = Field(default=None, description="https://www.w3.org/TR/skos-primer/#secassociative", alias="http://www.w3.org/2004/02/skos/core#exactMatch")
    http___www_w3_org_2004_02_skos_coreclose_match: Optional[List[Dict[str, Any]]] = Field(default=None, description="https://www.w3.org/TR/skos-primer/#secassociative", alias="http://www.w3.org/2004/02/skos/core#closeMatch")
    http___www_w3_org_2004_02_skos_corebroad_match: Optional[List[Dict[str, Any]]] = Field(default=None, description="https://www.w3.org/TR/skos-primer/#secassociative", alias="http://www.w3.org/2004/02/skos/core#broadMatch")
    http___www_w3_org_2004_02_skos_corenarrow_match: Optional[List[Dict[str, Any]]] = Field(default=None, description="https://www.w3.org/TR/skos-primer/#secassociative", alias="http://www.w3.org/2004/02/skos/core#narrowMatch")
    http___www_w3_org_2004_02_skos_corerelated_match: Optional[List[Dict[str, Any]]] = Field(default=None, description="https://www.w3.org/TR/skos-primer/#secassociative", alias="http://www.w3.org/2004/02/skos/core#relatedMatch")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["@id", "http://www.w3.org/2004/02/skos/core#broader", "http://www.w3.org/2004/02/skos/core#narrower", "http://www.w3.org/2004/02/skos/core#exactMatch", "http://www.w3.org/2004/02/skos/core#closeMatch", "http://www.w3.org/2004/02/skos/core#broadMatch", "http://www.w3.org/2004/02/skos/core#narrowMatch", "http://www.w3.org/2004/02/skos/core#relatedMatch"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RelationshipOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RelationshipOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "http://www.w3.org/2004/02/skos/core#broader": obj.get("http://www.w3.org/2004/02/skos/core#broader"),
            "http://www.w3.org/2004/02/skos/core#narrower": obj.get("http://www.w3.org/2004/02/skos/core#narrower"),
            "http://www.w3.org/2004/02/skos/core#exactMatch": obj.get("http://www.w3.org/2004/02/skos/core#exactMatch"),
            "http://www.w3.org/2004/02/skos/core#closeMatch": obj.get("http://www.w3.org/2004/02/skos/core#closeMatch"),
            "http://www.w3.org/2004/02/skos/core#broadMatch": obj.get("http://www.w3.org/2004/02/skos/core#broadMatch"),
            "http://www.w3.org/2004/02/skos/core#narrowMatch": obj.get("http://www.w3.org/2004/02/skos/core#narrowMatch"),
            "http://www.w3.org/2004/02/skos/core#relatedMatch": obj.get("http://www.w3.org/2004/02/skos/core#relatedMatch")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


